repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
      exclude: ^data/*
  -   id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      language: python
      types: [python]
      stages: [commit]

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      name: flake8
      language: python
      types: [python]
      stages: [commit]
      require_serial: true

- repo: local
  hooks:
    - id: pylint
      name: pylint
      language: python
      types: [python]
      entry: pylint src/
      require_serial: true
