repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  -   id: check-yaml
  -   id: end-of-file-fixer
  -   id: trailing-whitespace

- repo: https://github.com/PyCQA/isort
  rev: "5.12.0"
  hooks:
    - id: isort
      name: isort (python)

- repo: https://github.com/PyCQA/flake8
  rev: "6.0.0"
  hooks:
    - id: flake8
      name: flake8

- repo: https://github.com/PyCQA/pylint
  rev: v2.17.0
  hooks:
    - id: pylint
      name: pylint

exclude: data/
